<?php

namespace App\Models\Book;

use Illuminate\Database\Eloquent\Model;
use Encore\Admin\Facades\Admin;

class Book extends Model
{
    /*
     * 所属类型
     */
    public function category()
    {
        return $this->hasOne(Category::class);
    }

    /**
     *保存
     */
    public function save(array $options = [])
    {
        $this->creator=Admin::user()->name;
        $this->created_at=now();
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
