<?php

namespace App\Models\Basic;

use Encore\Admin\Facades\Admin;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;
use Encore\Admin\Traits\AdminBuilder;
use Encore\Admin\Traits\ModelTree;

class Department extends Model
{
    use ModelTree, AdminBuilder;
    protected $fillable = ['name','description','order','parent_id'];


    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->setParentColumn('parent_id');
        $this->setOrderColumn('order');
        $this->setTitleColumn('name');
    }

    /**
     *保存
     */
    public function save(array $options = [])
    {
        $this->creator=Admin::user()->name;
        $this->created_at=now();
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
